title: ZenHomeFlow
description: Harmonize your home with design and energy
author: Matthew Benavidez
url: "https://matthewbenavidez.github.io"
# baseurl is omitted since you renamed the repo

permalink: /:year/:month/:day/:title.html

theme: minima

