title: ZenHomeFlow
description: Harmonize your home with design and energy
author: Matthew Benavidez
url: "https://matthewbenavidez.github.io"


paginate: 5
paginate_path: "/page:num"
permalink: /:year/:month/:day/:title.html

theme: minima

plugins:
  - jekyll-paginate
